apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-zjua
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-zjua@sha256:c898343bc061f2619e23d80fa269320d3cafb8e7f6340069b67a716eba013f8d
        name: my-python
        resources: {}
status: {}
